Repository wecode-bootcamp-korea/20-1st-LIFEFRIENDS-backend, pull requests merged in 2021-05, with the labels that each got.

#1 Feature/products
  .gitignore
  db_uploader.py
  life_friends/settings.py
  life_friends/urls.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210512_0513.py
  orders/migrations/0003_alter_selectedproduct_table.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210512_0513.py
  products/migrations/0003_auto_20210513_0346.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/0001_initial.py
  reviews/migrations/0002_auto_20210512_0513.py
  reviews/migrations/0003_alter_reviewimage_table.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210512_0513.py
  users/migrations/0003_alter_usercoupon_table.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [20기 양영건] 사용자 회원가입 및 로그인 API
  life_friends/urls.py
  orders/migrations/0002_auto_20210512_0454.py
  products/migrations/0002_auto_20210512_0454.py
  reviews/migrations/0002_auto_20210512_0454.py
  users/migrations/0002_auto_20210512_0454.py
  users/urls.py
  users/validations.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [20기 양영건] model 수정을 위한 PR
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210512_0454.py
  orders/migrations/0002_auto_20210512_0513.py
  orders/migrations/0003_alter_selectedproduct_table.py
  orders/models.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210512_0454.py
  products/migrations/0002_auto_20210512_0513.py
  products/migrations/0003_auto_20210513_0346.py
  reviews/migrations/0001_initial.py
  reviews/migrations/0002_auto_20210512_0454.py
  reviews/migrations/0002_auto_20210512_0513.py
  reviews/migrations/0003_alter_reviewimage_table.py
  reviews/models.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210512_0454.py
  users/migrations/0002_auto_20210512_0513.py
  users/migrations/0003_alter_usercoupon_table.py
Labels: Status: 리뷰 요청

#6 [20기 양영건] model 수정을 위한 PR (2)
  orders/migrations/0002_auto_20210517_0821.py
  orders/models.py
  reviews/migrations/0002_auto_20210517_0821.py
  reviews/migrations/0003_auto_20210517_1108.py
  reviews/models.py
Labels: Status: Accepted

#3 [20기 양영건] 카테고리 별 제품 분류 API
  decorators.py
  life_friends/urls.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/urls.py
  products/views.py
  reviews/migrations/0001_initial.py
  reviews/migrations/__init__.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/urls.py
  users/validations.py
  users/views.py
Labels: Status: Accepted

#8 [20기 신승호] 상품 검색 API
  db_uploader.py
  products/urls.py
  products/views.py
  users/views.py
Labels: Status: Accepted

#7 [20기 신승호] 메타데이터 API
  products/urls.py
  products/views.py
Labels: Status: Conflict 발생

#9 [20기 신승호] 상품 정보 API
  products/urls.py
  products/views.py
Labels: Status: Conflict 발생, Status: 수정 요청

#13 [20기 양영건] 장바구니 CRUD API
  life_friends/urls.py
  orders/urls.py
  orders/views.py
Labels: Status: 리뷰 요청

#12 [20기 신승호] 상품 구매 API
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청
